### ISSUE TITLE
Build not possible

### ISSUE THREAD

**Issue by dungm4am** [jetcz/eToroAccountStatementProcessor#1]
Hi, 

Thanks for creating this, it might be very useful! However I tried to build and got an error: 

Error	CS1061	

'IEnumerable<ClosedPositionViewRecord>' does not contain a definition for 'Append' and no accessible extension method 'Append' accepting a first argument of type 'IEnumerable<ClosedPositionViewRecord>' could be found (are you missing a using directive or an assembly reference?)

I'm no good at C# (had school long ago) ... so please, any solution? :) 

Thanks!

**Comment by jetcz** [comment]
Hi,
Thats weird. Maybe try (re)installing .NET framework 4.8?

**Comment by dungm4am** [comment]
Thank you, it worked! :) 
(Windows pretend that 4.8 is installed however Visual studio targetted the build for some reason to version 4.6.1 only. Maximal version available in VS is 4.7.2, still, reinstalling 4.8 wasn't possible. Fortunately, 4.7.2 was enough).

**Comment by jetcz** [comment]
I think you need also latest Visual studio 2019
